### ISSUE TITLE
CPP-Aandroid 闪退

### ISSUE THREAD

**Issue by tinybearc** [sdkbox/obselete-sdkbox-SdkboxAds-sample#4]
### SdkboxAds 版本：2.1.2.1

真机上运行会提示该程序已关闭。

log：
~~~
03-18 00:46:11.575: I/Vungle(20426): Vungle AdUnit initialized
03-18 00:46:11.578: W/GooglePlayServicesUtil(20426): Google Play services is missing.
03-18 00:46:11.703: W/art(20426): Attempt to remove non-JNI local reference, dumping thread
03-18 00:46:11.719: W/AwContents(20426): onDetachedFromWindow called when already detached. Ignoring
03-18 00:46:11.737: D/EgretLoader(20426): EgretLoader(Context context)
03-18 00:46:11.738: D/EgretLoader(20426): The context is not activity
03-18 00:46:11.750: W/art(20426): Attempt to remove non-JNI local reference, dumping thread
03-18 00:46:11.792: D/SdkboxAds(20426): Registered _ad_nits
03-18 00:46:13.783: W/GooglePlayServicesUtil(20426): Google Play services is missing.
03-18 00:46:14.229: E/com.bee7.sdk.publisher.m(20426): Failed to send gms failed event
03-18 00:46:14.229: E/com.bee7.sdk.publisher.m(20426): org.apache.http.client.HttpResponseException: Error in response: HTTP/1.1 404 Not Found
03-18 00:46:14.229: E/com.bee7.sdk.publisher.m(20426): 	at com.bee7.sdk.common.a.a(AbstractBackendCommunication.java:497)
03-18 00:46:14.229: E/com.bee7.sdk.publisher.m(20426): 	at com.bee7.sdk.common.a.a(AbstractBackendCommunication.java:468)
03-18 00:46:14.229: E/com.bee7.sdk.publisher.m(20426): 	at com.bee7.sdk.common.a.a(AbstractBackendCommunication.java:432)
03-18 00:46:14.229: E/com.bee7.sdk.publisher.m(20426): 	at com.bee7.sdk.publisher.m.a(PublisherWorker.java:1922)
03-18 00:46:14.229: E/com.bee7.sdk.publisher.m(20426): 	at com.bee7.sdk.common.v.run(AbstractWorker.java:201)
03-18 00:46:14.229: E/com.bee7.sdk.publisher.m(20426): 	at android.os.Handler.handleCallback(Handler.java:739)
03-18 00:46:14.229: E/com.bee7.sdk.publisher.m(20426): 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-18 00:46:14.229: E/com.bee7.sdk.publisher.m(20426): 	at android.os.Looper.loop(Looper.java:148)
03-18 00:46:14.229: E/com.bee7.sdk.publisher.m(20426): 	at android.os.HandlerThread.run(HandlerThread.java:61)
03-18 00:46:14.236: E/com.bee7.sdk.publisher.m(20426): Google Play Service not available: 1
03-18 00:46:14.239: I/art(20426): Rejecting re-init on previously-failed class java.lang.Class<com.vungle.publisher.location.GoogleLocationClientDetailedLocationProvider>
03-18 00:46:21.394: W/Ads(20426): There was a problem getting an ad response. ErrorCode: 0
03-18 00:46:21.498: W/Ads(20426): There was a problem getting an ad response. ErrorCode: 0
03-18 00:46:21.510: W/Ads(20426): There was a problem getting an ad response. ErrorCode: 0
03-18 00:46:21.549: W/Ads(20426): There was a problem getting an ad response. ErrorCode: 0
03-18 00:46:21.579: W/Ads(20426): There was a problem getting an ad response. ErrorCode: 0
03-18 00:46:30.864: W/VungleNetwork(20426): java.net.UnknownHostException: Unable to resolve host "cdn-lb.vungle.com": No address associated with hostname
03-18 00:46:31.440: I/art(20426): Thread[2,tid=20431,WaitingInMainSignalCatcherLoop,Thread*=0xaec6e000,peer=0x12c200a0,"Signal Catcher"]: reacting to signal 3
03-18 00:46:32.076: I/art(20426): Wrote stack traces to '/data/anr/traces.txt'
03-18 00:46:36.888: W/VungleNetwork(20426): java.net.UnknownHostException: Unable to resolve host "cdn-lb.vungle.com": No address associated with hostname

~~~

**Comment by yinjimmy** [comment]
The error is:

```
D/MtkOmxCore(15182): free_inst_handle dlclose(0x0xf3f94dc4), free(0x0xab6ab024)
D/AndroidRuntime(31562): Shutting down VM
E/AndroidRuntime(31562): FATAL EXCEPTION: main
E/AndroidRuntime(31562): Process: org.cocos2dx.sdkboxads, PID: 31562
E/AndroidRuntime(31562): java.lang.NoSuchMethodError: No static method d(Ljava/lang/String;Ljava/lang/String;)V in class Lcom/sdkbox/plugin/SdkboxLog; or its super classes (declaration of 'com.sdkbox.plugin.SdkboxLog' appears in /data/app/org.cocos2dx.sdkboxads-1/base.apk)
E/AndroidRuntime(31562): 	at com.sdkbox.plugin.PluginSdkboxAds$1.run(PluginSdkboxAds.java:206)
E/AndroidRuntime(31562): 	at android.os.Handler.handleCallback(Handler.java:815)
E/AndroidRuntime(31562): 	at android.os.Handler.dispatchMessage(Handler.java:104)
E/AndroidRuntime(31562): 	at android.os.Looper.loop(Looper.java:194)
E/AndroidRuntime(31562): 	at android.app.ActivityThread.main(ActivityThread.java:5549)
E/AndroidRuntime(31562): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31562): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(31562): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
E/AndroidRuntime(31562): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
D/ACodec  (31562): Now uninitialized
```

**Comment by yinjimmy** [comment]
update sdkboxads and plugins, v2.1.2.4.

```
D/AndroidRuntime( 2497): Shutting down VM
E/AndroidRuntime( 2497): FATAL EXCEPTION: main
E/AndroidRuntime( 2497): Process: org.cocos2dx.sdkboxads, PID: 2497
E/AndroidRuntime( 2497): java.lang.AbstractMethodError: abstract method "boolean com.sdkbox.reflect.AdUnit.play(java.lang.String, com.sdkbox.plugin.JSON)"
E/AndroidRuntime( 2497): 	at com.sdkbox.plugin.PluginSdkboxAds$2.run(PluginSdkboxAds.java:280)
E/AndroidRuntime( 2497): 	at android.os.Handler.handleCallback(Handler.java:815)
E/AndroidRuntime( 2497): 	at android.os.Handler.dispatchMessage(Handler.java:104)
E/AndroidRuntime( 2497): 	at android.os.Looper.loop(Looper.java:194)
E/AndroidRuntime( 2497): 	at android.app.ActivityThread.main(ActivityThread.java:5549)
E/AndroidRuntime( 2497): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 2497): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 2497): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
E/AndroidRuntime( 2497): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
I/octvm_klo( 3656): klo lock
I/WhetstoneService(16226): Receive am_crash event for pid: 2497
```
